Question 1
==========
Lets start by explaining the following code:

In [18]:
# Part A
import numpy as np 
A = np.array([[1,3,3],
            [2,2,-2],
            [-2,2,1]], dtype= float)
m, n = A.shape
Q = np.zeros((m,n))
R = np.zeros((n,n))

for j in range(n):
    v = A[:, j]
    for i in range(j):
        R[i,j] = np.dot(Q[:, i], A[:,j])
        v = v - R[i,j] * Q[:,i]
    R[j,j] = np.linalg.norm(v) 
    Q[:,j] = v/R[j,j] 
np.linalg.inv(Q)
print(Q)
print(R)

# Part B
Q_np, R_np = np.linalg.qr(A)
print(Q_np)
print(R_np)

[[ 0.33333333  0.66666667  0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]
 [-0.66666667  0.66666667 -0.33333333]]
[[ 3.  1. -1.]
 [ 0.  4.  2.]
 [ 0.  0.  3.]]
[[-0.33333333 -0.66666667  0.66666667]
 [-0.66666667 -0.33333333 -0.66666667]
 [ 0.66666667 -0.66666667 -0.33333333]]
[[-3. -1.  1.]
 [ 0. -4. -2.]
 [ 0.  0.  3.]]


Part A (COME BACK)
------
    This code creates first the a matrix as an array in numpy, then it finds its dimensions. Next we set up a matrix of zeros for each correspoinding Q and R which we will then fill in our double for loop. In the first half we are just telling which sections of our matrix we want to be filled by dot porudct of our Q and A where then we subtract the current vertix we are wroking with. Finally over the first look we then normalize that vertex and then plug that into our R and then normailze the whole vertex in our Q. 
Part B
------
    Done above
Part C
------
    It looks like we have oppostie signs for our first two columbs of Q and R. 
Part D
------

In [24]:
A = np.array([[-1,-3,1],
             [-2,2,-2],
             [2,-2,0],
             [4,0,-2]])
Q_red, R_red = np.linalg.qr(A, mode='reduced')

Q_comp, R_comp = np.linalg.qr(A, mode='complete')
print(Q_red)
print(Q_comp)
print(R_red)
print(R_comp)

[[-0.2  0.8 -0.4]
 [-0.4 -0.4 -0.8]
 [ 0.4  0.4 -0.2]
 [ 0.8 -0.2 -0.4]]
[[-0.2  0.8 -0.4  0.4]
 [-0.4 -0.4 -0.8 -0.2]
 [ 0.4  0.4 -0.2 -0.8]
 [ 0.8 -0.2 -0.4  0.4]]
[[ 5. -1. -1.]
 [ 0. -4.  2.]
 [ 0.  0.  2.]]
[[ 5. -1. -1.]
 [ 0. -4.  2.]
 [ 0.  0.  2.]
 [ 0.  0.  0.]]
